baseURL = "https://em230418.github.io/"
title = "Евгений Молотов"
pygmentsUseClasses = true
uglyurls = false
disablePathToLower = true
defaultContentLanguage = "ru"

[permalinks]
blog = "/:year/:month/:day/:filename"

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
ordered = true

[mediaTypes]
[outputs]
section = ["HTML", "RSS"]
